// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfoawG0as8DpkpwOMor5WIgnfD73mv4o',
    appId: '1:418116388570:web:80029925ce952a238787e3',
    messagingSenderId: '418116388570',
    projectId: 'journal-7fafc',
    authDomain: 'journal-7fafc.firebaseapp.com',
    storageBucket: 'journal-7fafc.firebasestorage.app',
    measurementId: 'G-NECXK98FQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBypwgFo0nP4OvjnYbipc9e34VH-zOzNd8',
    appId: '1:418116388570:android:31b434e497b51a548787e3',
    messagingSenderId: '418116388570',
    projectId: 'journal-7fafc',
    storageBucket: 'journal-7fafc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyfoawG0as8DpkpwOMor5WIgnfD73mv4o',
    appId: '1:418116388570:web:0776410cb9a9b7df8787e3',
    messagingSenderId: '418116388570',
    projectId: 'journal-7fafc',
    authDomain: 'journal-7fafc.firebaseapp.com',
    storageBucket: 'journal-7fafc.firebasestorage.app',
    measurementId: 'G-EVSH38DWM9',
  );
}
